site_name: Team 11 - FitPal
site_url: https://team11.com
nav:
  - Home: index.md
  - Login: login.md
  - Register: register.md
  - Delete: delete.md
  - InputOutputFlashCards: inputOutputFlashCards.md
  - Share Flash Card: shareFlashcards.md
  - RenderNotes: renderNotes.md
  - Share Notes: shareNotes.md
  - To-do List: todolist.md
  - Pomodoro Timer: pomodorotimer.md
  - Track Hour: trackHours.md
theme: readthedocs
